
def close_connection(exception):